// <auto-generated />
using System;
using CAR_RENTAL_00015775.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

//------ 00015775 ---------//

namespace CAR_RENTAL_00015775.Migrations
{
    [DbContext(typeof(CarRentalDbContext))]
    partial class CarRentalDbContextModelSnapshot : ModelSnapshot
    {
        //------ 00015775 ---------//
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            //------ 00015775 ---------//

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);
            //------ 00015775 ---------//
            modelBuilder.Entity("CAR_RENTAL_00015775.Models.Cars_00015775", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    //------ 00015775 ---------//

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Customers_00015775CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("RentalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");
                    //------ 00015775 ---------//

                    b.HasKey("CarId");

                    b.HasIndex("Customers_00015775CustomerId");

                    b.ToTable("Cars_00015775");
                });

            modelBuilder.Entity("CAR_RENTAL_00015775.Models.Customers_00015775", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers_00015775");
                });
            //------ 00015775 ---------//

            modelBuilder.Entity("CAR_RENTAL_00015775.Models.Cars_00015775", b =>
                {
                    b.HasOne("CAR_RENTAL_00015775.Models.Customers_00015775", "Customers_00015775")
                        .WithMany()
                        .HasForeignKey("Customers_00015775CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customers_00015775");
                });
#pragma warning restore 612, 618
        }
    }
}
//------ 00015775 ---------//
